-- suppliers: alla leverantörsnamn ur källfilerna (idempotent)
insert into suppliers (name, slug) values
('2Work Sverige AB', '2work-sverige-ab'),
('A-Karriär Sweden AB', 'a-karriar-sweden-ab'),
('AAA Livek Sjuhärad AB', 'aaa-livek-sjuharad-ab'),
('AAA Work&Coaching i Sverige AB', 'aaa-work-coaching-i-sverige-ab'),
('AB Ability Coaching', 'ab-ability-coaching'),
('AB Arbetskonsulterna i Sverige', 'ab-arbetskonsulterna-i-sverige'),
('AB Coachgruppen Strömbergs', 'ab-coachgruppen-strombergs'),
('AB Effektiv Matchning', 'ab-effektiv-matchning'),
('AB Jobbredo Sverige', 'ab-jobbredo-sverige'),
('AB Jobbservice & Co', 'ab-jobbservice-co'),
('AB Taktik Sweden', 'ab-taktik-sweden'),
('ABF Progress AB', 'abf-progress-ab'),
('AHG Omställning AB', 'ahg-omstallning-ab'),
('AKG Sverige AB', 'akg-sverige-ab'),
('ALFA INSTANT AB', 'alfa-instant-ab'),
('Aaryati Consulting AB', 'aaryati-consulting-ab'),
('Abf Göteborg Vuxenutbildning AB', 'abf-goteborg-vuxenutbildning-ab'),
('Abf Halland', 'abf-halland'),
('Abl Konsult i Malmö AB', 'abl-konsult-i-malmo-ab'),
('Abra AB', 'abra-ab'),
('Academedia Eductus AB', 'academedia-eductus-ab'),
('Academicum Utbildning & Bemanning AB', 'academicum-utbildning-bemanning-ab'),
('Accepta Vi Almira AB', 'accepta-vi-almira-ab'),
('Addkomp AB', 'addkomp-ab'),
('Ademia AB', 'ademia-ab'),
('Advansi AB', 'advansi-ab'),
('Akadeva AB', 'akadeva-ab'),
('Allgencia AB', 'allgencia-ab'),
('Alma Folkhögskola Uppdrag AB', 'alma-folkhogskola-uppdrag-ab'),
('Amela Stockholm AB', 'amela-stockholm-ab'),
('ArbetsCentralen Bemanning Sverige AB', 'arbetscentralen-bemanning-sverige-ab'),
('ArbetsCentralen Sverige AB', 'arbetscentralen-sverige-ab'),
('ArbetsLagret AB', 'arbetslagret-ab'),
('Arbetscenter Stockholm AB', 'arbetscenter-stockholm-ab'),
('Arbetsglobala Konsult AB', 'arbetsglobala-konsult-ab'),
('Arbetsklivet AB', 'arbetsklivet-ab'),
('Arbetslivskraft Sverige AB', 'arbetslivskraft-sverige-ab'),
('Arbetslivsresurs Ar AB', 'arbetslivsresurs-ar-ab'),
('Arbetslivssupport Sverige AB', 'arbetslivssupport-sverige-ab'),
('Arbetsmedlarna i Sverige AB', 'arbetsmedlarna-i-sverige-ab'),
('Arbetsvägen Halland AB', 'arbetsvagen-halland-ab'),
('Arcus Utbildning & Jobbförmedling AB', 'arcus-utbildning-jobbformedling-ab'),
('Arena Matchning AB', 'arena-matchning-ab'),
('Arena Workforce AB', 'arena-workforce-ab'),
('Aros Folkbildningstjänst AB', 'aros-folkbildningstjanst-ab'),
('Aros Matchning och Utbildning AB', 'aros-matchning-och-utbildning-ab'),
('Asuria People Services ( Sweden ) AB', 'asuria-people-services-sweden-ab'),
('At Work Nordic AB', 'at-work-nordic-ab'),
('Aventus AB', 'aventus-ab'),
('Avilon AB', 'avilon-ab'),
('Avioto AB', 'avioto-ab'),
('Axelera Sverige AB', 'axelera-sverige-ab'),
('BETE Global Bemanning AB', 'bete-global-bemanning-ab'),
('Back To Work AB', 'back-to-work-ab'),
('Bahusia Utveckling AB', 'bahusia-utveckling-ab'),
('Best Bemanning & Rekrytering i Sverige AB', 'best-bemanning-rekrytering-i-sverige-ab'),
('Branteviks Gruppen AB', 'branteviks-gruppen-ab'),
('Business Performance Europe AB', 'business-performance-europe-ab'),
('Can Etablering KB', 'can-etablering-kb'),
('CenterLink Sverige AB', 'centerlink-sverige-ab'),
('City Service Sweden AB', 'city-service-sweden-ab'),
('Cleverex Jobbförmedling & Utbildning AB', 'cleverex-jobbformedling-utbildning-ab'),
('Clockwork Matchning AB', 'clockwork-matchning-ab'),
('Clustera Sverige AB', 'clustera-sverige-ab'),
('Coach, Ulrika Holmgren AB', 'coach-ulrika-holmgren-ab'),
('Connectas AB', 'connectas-ab'),
('Connectbase Coachning AB', 'connectbase-coachning-ab'),
('Connecto AB', 'connecto-ab'),
('CrownMatch AB', 'crownmatch-ab'),
('Curonova Consulting AB', 'curonova-consulting-ab'),
('Dream Matchning Väst AB', 'dream-matchning-vast-ab'),
('EHRAB ByggBemanning AB', 'ehrab-byggbemanning-ab'),
('ETU Match AB', 'etu-match-ab'),
('Enrival AB', 'enrival-ab'),
('Erigo Syd AB', 'erigo-syd-ab'),
('Euniq''em AB', 'euniq-em-ab'),
('Everystep AB', 'everystep-ab'),
('Eyes4work AB', 'eyes4work-ab'),
('Eyra Education AB', 'eyra-education-ab'),
('FAS Kliv konsult AB', 'fas-kliv-konsult-ab'),
('Fast Lane AB', 'fast-lane-ab'),
('Fiks Group AB', 'fiks-group-ab'),
('Finderz AB', 'finderz-ab'),
('Folkuniversitetet Stift Kurs- Verksamheten', 'folkuniversitetet-stift-kurs-verksamheten'),
('Folkuniversitetet Stift Kursverksamheten Vi', 'folkuniversitetet-stift-kursverksamheten-vi'),
('Folkuniversitetet Stift Kursverksamheten Vid Sto', 'folkuniversitetet-stift-kursverksamheten-vid-sto'),
('Folkuniversitetet Uppdrag Väst AB', 'folkuniversitetet-uppdrag-vast-ab'),
('Fortem HC i Stockholm AB', 'fortem-hc-i-stockholm-ab'),
('Framgångsförmedlingen AB', 'framgangsformedlingen-ab'),
('Funkisgruppen AB', 'funkisgruppen-ab'),
('Fören Furuboda Utbildning och Kompetenscentrum', 'foren-furuboda-utbildning-och-kompetenscentrum'),
('Granter AB', 'granter-ab'),
('Guldjobbet AB', 'guldjobbet-ab'),
('Göteborgs Kyrkliga Stadsmission Bistånd och Entr', 'goteborgs-kyrkliga-stadsmission-bistand-och-entr'),
('Haga Rekrytering AB', 'haga-rekrytering-ab'),
('Handelsakademin i Göteborg AB', 'handelsakademin-i-goteborg-ab'),
('HelloLilly AB', 'hellolilly-ab'),
('Hesore Consulting AB', 'hesore-consulting-ab'),
('Hivram AB', 'hivram-ab'),
('Hos Bois AB', 'hos-bois-ab'),
('Hyllie Park Talentbyrån AB', 'hyllie-park-talentbyran-ab'),
('INQLUDERA CJ AB', 'inqludera-cj-ab'),
('Inda Utveckling AB', 'inda-utveckling-ab'),
('Indarad AB', 'indarad-ab'),
('InfoReda AB', 'inforeda-ab'),
('Iris Hadar AB', 'iris-hadar-ab'),
('JABBO Bemanning AB', 'jabbo-bemanning-ab'),
('JOBTEAM KONSULT R.L.H. AB', 'jobteam-konsult-r-l-h-ab'),
('JTC Linked AB', 'jtc-linked-ab'),
('Jalla jobbcenter AB', 'jalla-jobbcenter-ab'),
('Job By Instep AB', 'job-by-instep-ab'),
('Job Generation Center Sweden AB', 'job-generation-center-sweden-ab'),
('JobRivers AB', 'jobrivers-ab'),
('Jobb Store i Sverige AB', 'jobb-store-i-sverige-ab'),
('Jobb- och studieguiden Sverige AB', 'jobb-och-studieguiden-sverige-ab'),
('JobbFokus Sverige AB', 'jobbfokus-sverige-ab'),
('Jobbcentrum Sverige AB', 'jobbcentrum-sverige-ab'),
('Jobbie Sverige AB', 'jobbie-sverige-ab'),
('Jobbklar Sverige AB', 'jobbklar-sverige-ab'),
('Jobbkompaniet Nova AB', 'jobbkompaniet-nova-ab'),
('Jobblotsen Sverige AB', 'jobblotsen-sverige-ab'),
('Jobblyftet AB', 'jobblyftet-ab'),
('Jobbmaskinen DistansMatchning AB', 'jobbmaskinen-distansmatchning-ab'),
('Jobbmäklarna i Sverige AB', 'jobbmaklarna-i-sverige-ab'),
('Jobbpunkten AB', 'jobbpunkten-ab'),
('Jobbstep in Sweden AB', 'jobbstep-in-sweden-ab'),
('Jobbstjärnan AB', 'jobbstjarnan-ab'),
('Jobbträffen Sverige AB', 'jobbtraffen-sverige-ab'),
('Jobcenter in Sweden AB', 'jobcenter-in-sweden-ab'),
('Jobcom Sweden AB', 'jobcom-sweden-ab'),
('Jobfind Sverige AB', 'jobfind-sverige-ab'),
('Jobfix Europe AB', 'jobfix-europe-ab'),
('Jobmax AB', 'jobmax-ab'),
('Jobready Stockholm AB', 'jobready-stockholm-ab'),
('Karmo i Sverige AB', 'karmo-i-sverige-ab'),
('Karriärkonsulten Sverige AB', 'karriarkonsulten-sverige-ab'),
('Karriärmentorn Tumba AB', 'karriarmentorn-tumba-ab'),
('Karriärsteget Sverige AB', 'karriarsteget-sverige-ab'),
('Karriärvägledarna i Sverige AB', 'karriarvagledarna-i-sverige-ab'),
('Kkp Bemanning AB', 'kkp-bemanning-ab'),
('Kolego AB', 'kolego-ab'),
('Kollega - matchning, rekrytering och bemanning A', 'kollega-matchning-rekrytering-och-bemanning-a'),
('Kompetens & Matchning Sverige AB', 'kompetens-matchning-sverige-ab'),
('Kompetenso AB', 'kompetenso-ab'),
('Kurera Framtid AB', 'kurera-framtid-ab'),
('LAVI gruppen AB', 'lavi-gruppen-ab'),
('Lernia Utbildning AB', 'lernia-utbildning-ab'),
('LinQs Jobbcenter AB', 'linqs-jobbcenter-ab'),
('Lycka Service AB', 'lycka-service-ab'),
('Lyckojobbet AB', 'lyckojobbet-ab'),
('Lönn-Sulic Mångfaldsmodeller AB', 'lonn-sulic-mangfaldsmodeller-ab'),
('M Möjligheternas Plats AB', 'm-mojligheternas-plats-ab'),
('MIRA Kompetens AB', 'mira-kompetens-ab'),
('Man måste Må AB', 'man-maste-ma-ab'),
('Manpower Matchning AB', 'manpower-matchning-ab'),
('Match and Move AB', 'match-and-move-ab'),
('Matchedin AB', 'matchedin-ab'),
('Matchia AB', 'matchia-ab'),
('Medborgarskolan Region Väst', 'medborgarskolan-region-vast'),
('MegaJobs AB', 'megajobs-ab'),
('Mentor Doris Grönlund AB', 'mentor-doris-gronlund-ab'),
('Mentrum AB', 'mentrum-ab'),
('Merit Utbildning Malmö AB', 'merit-utbildning-malmo-ab'),
('MiJob Bemanning & Rekrytering i Sverige AB', 'mijob-bemanning-rekrytering-i-sverige-ab'),
('Miljonbemanning AB', 'miljonbemanning-ab'),
('Miljonbemanning Restart AB', 'miljonbemanning-restart-ab'),
('Mindful AB', 'mindful-ab'),
('Misa AB', 'misa-ab'),
('Mon Avenue AB', 'mon-avenue-ab'),
('Montico Rekrytering AB', 'montico-rekrytering-ab'),
('Motivista Consulting AB', 'motivista-consulting-ab'),
('NYSTEP AB', 'nystep-ab'),
('NearYou Jobb & Utbildning i Sverige AB', 'nearyou-jobb-utbildning-i-sverige-ab'),
('Nordeast Kompetens och Bemanning AB', 'nordeast-kompetens-och-bemanning-ab'),
('Nordisk kompetens AB', 'nordisk-kompetens-ab'),
('Octarium AB', 'octarium-ab'),
('Olky AB', 'olky-ab'),
('Osynliga Jobb Sverige AB', 'osynliga-jobb-sverige-ab'),
('PB Industricoachen och Utbildning AB', 'pb-industricoachen-och-utbildning-ab'),
('Performiq AB', 'performiq-ab'),
('Personalpartner Sverige AB', 'personalpartner-sverige-ab'),
('Personalsupport Värmland AB', 'personalsupport-varmland-ab'),
('Power Elitgruppen AB', 'power-elitgruppen-ab'),
('Praecuro AB', 'praecuro-ab'),
('Progressa Education AB', 'progressa-education-ab'),
('Q-Mak AB', 'q-mak-ab'),
('RB Jobbförmedling AB', 'rb-jobbformedling-ab'),
('ROMAK AB', 'romak-ab'),
('RYS Jobb & Rekrytering AB', 'rys-jobb-rekrytering-ab'),
('Randstad Risesmart AB', 'randstad-risesmart-ab'),
('Rasendo AB', 'rasendo-ab'),
('Re:shift Jobb & Utbildning AB', 're-shift-jobb-utbildning-ab'),
('RustaMatcha Sverige AB', 'rustamatcha-sverige-ab'),
('Ryati AB', 'ryati-ab'),
('RÄTT Bemanning & Rekrytering i Sverige AB', 'ratt-bemanning-rekrytering-i-sverige-ab'),
('STEPTEAM LJI AB', 'stepteam-lji-ab'),
('STOCKHOLMS STADSMISSION', 'stockholms-stadsmission'),
('SamJobb- Samverkan och Jobb AB', 'samjobb-samverkan-och-jobb-ab'),
('SamJobbgruppen AB', 'samjobbgruppen-ab'),
('Sandson AB', 'sandson-ab'),
('Scandinavian Jobhunter Match AB', 'scandinavian-jobhunter-match-ab'),
('Sigma Academy AB', 'sigma-academy-ab'),
('Sigruns Consulting HB', 'sigruns-consulting-hb'),
('Skolbryggan AB', 'skolbryggan-ab'),
('Smart Matchning AB', 'smart-matchning-ab'),
('Snabbjobb MM AB', 'snabbjobb-mm-ab'),
('Start Introab AB', 'start-introab-ab'),
('Steps Jobbcenter AB', 'steps-jobbcenter-ab'),
('Stift Activa i Örebro län', 'stift-activa-i-orebro-lan'),
('Stift Pingstförsaml Skol- O Kursverksamhet', 'stift-pingstforsaml-skol-o-kursverksamhet'),
('Stift Väddö och Södertörn Folkhögskolor', 'stift-vaddo-och-sodertorn-folkhogskolor'),
('Studentconsulting Sweden AB (Publ)', 'studentconsulting-sweden-ab-publ'),
('Success yourway HB', 'success-yourway-hb'),
('Sverige Intermatch AB', 'sverige-intermatch-ab'),
('Sveriges Jobbcenter AB', 'sveriges-jobbcenter-ab'),
('Sweajobb Arbetsförmedling AB', 'sweajobb-arbetsformedling-ab'),
('Sweden Works AB', 'sweden-works-ab'),
('TETIKO AB', 'tetiko-ab'),
('Talenti Sverige AB', 'talenti-sverige-ab'),
('Transeo AB', 'transeo-ab'),
('Trim tab AB', 'trim-tab-ab'),
('Urkraft ASF AB', 'urkraft-asf-ab'),
('Utbildning i Norrbotten AB', 'utbildning-i-norrbotten-ab'),
('VitaVis AB', 'vitavis-ab'),
('WORKIE AB', 'workie-ab'),
('WeQube AB', 'weqube-ab'),
('Work & Coaching i Sverige AB', 'work-coaching-i-sverige-ab'),
('Work Education Sverige AB', 'work-education-sverige-ab'),
('Work Integration i Stockholm AB', 'work-integration-i-stockholm-ab'),
('Workmode AB', 'workmode-ab'),
('Worktasker AB', 'worktasker-ab'),
('Yes2work AB', 'yes2work-ab'),
('Yrkescentrum i Sverige AB', 'yrkescentrum-i-sverige-ab'),
('wayit Sverige AB', 'wayit-sverige-ab'),
('workfind Sverige AB', 'workfind-sverige-ab')
on conflict (name) do nothing;
